---
- name: New branch
  hosts: control_node
  vars:
    
  become: true

  tasks:
   - name: cd
     shell: 'cd eu-west-1'     
     
   - name: run terraform file
     shell: 'sudo terraform apply'
     register: command_output

   - debug:
        var: command_output
        


      
