apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kompose.cmd":"/snap/kompose/19/kompose-linux-amd64 convert","kompose.version":"1.21.0 (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"pythonapp"},"name":"pythonapp","namespace":"default"},"spec":{"ports":[{"name":"5000","port":8080,"targetPort":5000}],"selector":{"io.kompose.service":"pythonapp"}},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    io.kompose.service: pythonapp
  name: pythonapp
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: pythonapp
  # type: LoadBalancer
status:
  loadBalancer: {}


