---
- name: Install Cowrie SSH Honeypot
  hosts: all
  become: yes

  vars:
    cowrie_repo: "https://github.com/cowrie/cowrie.git"
    cowrie_install_dir: "/opt/cowrie"
    python_venv_dir: "/opt/cowrie/venv"

  tasks:
    - name: Ensure the apt package index is updated
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-venv
          - python3-dev
          - libssl-dev
          - libffi-dev
          - libmpfr-dev
          - libgmp-dev
        state: present

    - name: Clone Cowrie repository
      git:
        repo: "{{ cowrie_repo }}"
        dest: "{{ cowrie_install_dir }}"
        version: master

    - name: Create a Python virtual environment
      command: python3 -m venv "{{ python_venv_dir }}"
      args:
        creates: "{{ python_venv_dir }}/bin/activate"

    - name: Install required Python packages
      pip:
        requirements: "{{ cowrie_install_dir }}/requirements.txt"
        virtualenv: "{{ python_venv_dir }}"

    - name: Copy cowrie.cfg
      copy:
        src: "{{ cowrie_install_dir }}/cowrie.cfg.dist"
        dest: "{{ cowrie_install_dir }}/cowrie.cfg"
        remote_src: yes

    - name: Create cowrie start script
      copy:
        dest: /etc/systemd/system/cowrie.service
        content: |
          [Unit]
          Description=Cowrie SSH/Telnet Honeypot
          After=network.target

          [Service]
          User=root
          WorkingDirectory={{ cowrie_install_dir }}
          ExecStart={{ python_venv_dir }}/bin/python {{ cowrie_install_dir }}/bin/cowrie start
          ExecStop={{ python_venv_dir }}/bin/python {{ cowrie_install_dir }}/bin/cowrie stop

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon to read new Cowrie service
      command: systemctl daemon-reload

    - name: Enable and start Cowrie service
      service:
        name: cowrie
        state: started
        enabled: yes

