---
- name: Install Wazuh agent
  hosts: all
  become: yes
 
  tasks:
    - name: Add Wazuh repository key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present
     
    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
     
    - name: Update apt cache
      apt:
        update_cache: yes
     
    - name: Install Wazuh agent
      apt:
        name: wazuh-agent
        state: present
     
    - name: Configure Wazuh agent
      copy:
        src: ossec.conf
        dest: /var/ossec/etc/ossec.conf
      notify:
        - restart wazuh-agent
     
  handlers:
    - name: restart wazuh-agent
      service:
        name: wazuh-agent
        state: restarted
