# Use the official Python base image with tag 3.9
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file and install the dependencies
COPY requirements.txt .

RUN pip install -r requirements.txt

# Copy the Flask application code into the container
COPY . .

# Expose the port that the Flask app is listening on
EXPOSE 5000

# Set the environment variable for Flask
ENV FLASK_APP=app.py

